# Generated by Django 3.2.4 on 2023-05-30 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
