# Generated by Django 3.2.4 on 2023-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20230530_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=50),
        ),
    ]
